INSERT INTO `dentist` (`dentistID`, `fname`, `lname`, `sex`, `address`, `licenseID`, `email`, `telp`, `userid`) VALUES
(12234, 'Suryandari', 'Puspita', 'F', 'Bekasi', 2147483647, 'suryandari@gmail.com', '0856918324556', NULL),
(22453, 'Raihan', 'Basuki', 'M', 'Jl. Kebangsaan Negara, No. 14', 2147483647, 'wiloso1003@gmail.com', '085691887072', NULL),
(33213, 'Raditya', 'Permadi', 'M', 'Tangerang Selatan', 2147483647, 'radi@gmail.com', '085691832499', NULL);

INSERT INTO `user` (`userid`, `email`, `password`, `name`, `role`, `username`) VALUES
(0, 'fwdew@hotmail.com', '$2y$10$DDC6xcVq/Dh83yyKlygsjOxgHARQvvjlN7DR5l/81GNEri9DWkBUO', 'admin', 'admin', 'admin'),
(1, 'raihansultan.pashabasuki@stude', '$2y$10$kwsyeVUuVth15rfVuRhPr.l7LBD1BGlQIVJGxhieOgkvq/RnQdVN2', 'Aku Pasien', 'patient', 'patient'),
(13, 'wiloso1003@whipjoy.com', '$2y$10$ePAVkxPjgy/JtXhgAizosu9f1dkbGauNg.aj2snucdni53w9dNviC', 'Aku Dentist', 'dentist', 'dentist');

INSERT INTO `treatment` (`namaTreatment`, `deskripsi`, `hargaTreatment`, `idTreatment`) VALUES
('Bleaching Gigi', 'Bleaching Gigi atau pemutihan gigi merupakan prosedur estetika yang digunakan untuk membuat permukaan gigi tampak lebih putih, dan bersih. Tidak perlu khawatir bleahing gigi tidak menyebabkan kerusakan pada permukaan gigi. Namun perlu diketahui efek bleaching gigi tidak bersifat permanen dan bisa bertahan hingga beberapa bulan hingga tiga tahun. Durasi tergantung bagaimana kita menjaga kesehatan gigi kita dengan menjaga konsumsi makanan atau minuman yang bisa menyebabkan gigi kuning.\r\n\r\n', 4500000, '1'),
('Inderect Veneer', 'Veneer adalah cangkang tipis yang ditempelkan pada bagian depan gigi untuk menganggtikan beberapa enamel yang terkikis, Sedankan Inderect veneer biasanya menggunakan bahan porcelain yang lebih kuat dan hasilnya lebih halus.', 4000000, '10'),
('Penambalan Gigi', 'Tambal gigi adalah perawatan yang dilakukan untuk memperbaiki gigi rusak atau gigi berlubang. Tambal gigi dilakukan dengan melakukan prosedur memasukan bahan tambalan ke bagian gigi yang rusak atau berlubang. Tambal gigi akan mengebalikan bentuk dan kondisi gigi seperti semula.\r\n\r\n', 500000, '11'),
('Pencabutan Gigi Bungsu', 'Operasi Gigi Bungsu adalah tindakan untuk mencabut gigi bungsu yang tumbuh di sudut belakang mulut bagian atas dan bawah. Operasi ini biasanya dilakukan ketika pertumbuhan gigi bungsu berpotensi menyebabkan masalah seperti, infeksi, gigi berlubang, atau kerusakan gigi dan tulang disekitarnya.', 3000000, '12'),
('Scalling Gigi', 'Scaling Gigi adalah prosedur untuk melakukan pembersihan karang gigi. Karang gigi terbentuk dari tumpukan plak yang menempel pada permukaan gigi. Karang gigi yang dibiarkan akan membuat tampilan gigi menjadi tampak kusam dan berwarna kecoklatan. Selain itu, karang gigi yang mengeras, biasanya sulit untuk dibersihkan.', 600000, '13'),
('Direct Veneer', 'Veneer adalah cangkang tipis yang ditempelkan pada bagian depan gigi untuk menganggtikan beberapa enamel yang terkikis, Direct Veneer artinya pemasangan veneer secara langsung pada pasien menggunakan bahan resin komposit.\r\n\r\n', 600000, '2'),
('Behel Gigi (Ceramic)', 'Kawat Gigi atau biasa disebut sebagai Behel adalah alat berbasis kawat yang digunakan oleh ortodontis untuk memperbaiki gigi atau rahang yang tidak rata dan gigi yang bertumpuk. Tujuan utama dari pemasangan kawat gigi ini sendiri adalah untuk menyelaraskan gigi dan rahang agar dapat menggigit makanan dengan baik dan menghasilkan senyum yang indah. Ortho dengan berbahan ceramic ini yang sewarna dengan gigi, sehingga tampilan behel menyatu dengan warna gigi, cocok digunakan pada orang yang mementingkan estetik pada pekerjaaanya.', 10000000, '3'),
('Behel Gigi (Metal)', 'Kawat Gigi atau biasa disebut sebagai Behel adalah alat berbasis kawat yang digunakan oleh ortodontis untuk memperbaiki gigi atau rahang yang tidak rata dan gigi yang bertumpuk. Tujuan utama dari pemasangan kawat gigi ini sendiri adalah untuk menyelaraskan gigi dan rahang agar dapat menggigit makanan dengan baik dan menghasilkan senyum yang indah. Ortho ini berbahan metal dan umum digunakan oleh kebanyak orang untuk memasang behel.', 6000000, '4'),
('Behel Gigi (Sapphire)', 'Kawat Gigi atau biasa disebut sebagai Behel adalah alat berbasis kawat yang digunakan oleh ortodontis untuk memperbaiki gigi atau rahang yang tidak rata dan gigi yang bertumpuk. Tujuan utama dari pemasangan kawat gigi ini sendiri adalah untuk menyelaraskan gigi dan rahang agar dapat menggigit makanan dengan baik dan menghasilkan senyum yang indah. Behel ini berbahan Sapphire yang sangat cocok untuk orang yang mementingkan estetika. Material berbahan sapphire memiliki kekuatan sama layaknya seperti behel berbahan logam atau metal. Sehingga sapphire merupakan kombinasi antara fungsi estetika ceramic dengan fungsi kekuatan dari behel berbahan logam atau metal. Dengan begitu behel transparan jenis behel sapphire bisa menjadi pilihan yang sangat tepat untuk perawatan.\r\n\r\n', 14000000, '5'),
('Gigi Palsu (Emax)', 'Emax adalah salah satu bahan yang dapat digunakan untuk gigi palsu, bahan ini terbuat dari titanium. Memiliki ketahanan yang sangat tangguh dan sangat cocok dipakai karena mudah dibentuk dan memiliki warna yang sangat mirip dengan gigi asli. Serta memiliki nilai estetik namun nilai estetiknya tidak lebih tinggi dari gigi palsu dengan bahan Zirconia.\r\n\r\n', 4000000, '6'),
('Gigi Palsu (PFM)', 'Gigi tiruan permanen bahan PFM adalah salah satu jenis gigi tiruan dengan bahan metal yang diindikasikan pada pasien yang kehilangan gigi aslinya, dan sangat disarankan untuk gigi belakang.\r\n\r\n', 2000000, '7'),
('Gigi Palsu (Zirconia)', 'Zirconia adalah salah satu bahan yang dapat digunakan untuk gigi palsu, bahan ini terbuat dari titanium. Memiliki ketahanan yang sangat tangguh dan sangat cocok dipakai karena mudah dibentuk dan memiliki warna yang sangat mirip dengan gigi asli. Serta memiliki nilai estetik yang tinggi.', 5000000, '8'),
('Gigi Palsu Lepasan', 'Gigi palsu lepasan adalah gigi tiruan yang bisa dilepas-pasang, gigi palsu lepasan ini memiliki fungsi untuk menggantikan gigi asli yang hilang ataupun yang keropos. Gigi palsu lepasan akan dibuat sangat mirip dengan gigi asli agar tampilan tampak sesuai, sehingga pengguna gigi palsu lepasan tidak perlu merasa takut akan tampilan yang berubah. Gigi palsu lepasan menjadi salah satu cara merapikan gigi jika terdapat banyak gigi yang hilang. Tak hanya untuk kepentingan estetika, pemasangan gigi palsu lepasan juga berfungsi sebagai gigi tiruan untuk mengembalikan kemampuan seseorang untuk mengunyah ataupun berbicara secara normal.', 2000000, '9');
